padok-team/burrito

Dockerfile

Fixes #84.
https://github.com/padok-team/burrito/blob/f2156f542f1e7cdbadb70c2c0b9c64750f35a783/Dockerfile#L2
https://github.com/padok-team/burrito/blob/f2156f542f1e7cdbadb70c2c0b9c64750f35a783/Dockerfile#L36
The SHA256 digests are the ones of the multi-platform image's manifest, obtained with the two followings commands as of May 14th, 2023:
```
docker buildx imagetools inspect golang:1.19.9
docker buildx imagetools inspect alpine:3.18.0
```
This enables the Docker image to be built with these fixed versions on any platform supported by the referenced manifests.
Fixes #124.
By using `alpine:3.18.0` instead of `golang:alpine`, the size decreases from ~390MB to ~96MB.
Adding the `--no-cache` option reduces the image only by ~1.5MB but is common practice.
Now the final image has a size of …

feat(docker): Improve Dockerfile

---

cmd/runner/start.go
internal/burrito/burrito.go
internal/burrito/runner.go
internal/controllers/terraformlayer/conditions.go
internal/controllers/terraformlayer/controller_test.go
internal/controllers/terraformpullrequest/states.go
internal/runner/runner.go
internal/webhook/github/provider.go
internal/webhook/gitlab/provider.go

fix(layer): handle terraform errors in runner

---

internal/burrito/config/config.go
internal/controllers/manager.go
internal/controllers/terraformpullrequest/comment/default.go
internal/controllers/terraformpullrequest/github/provider.go
internal/controllers/terraformpullrequest/gitlab/provider.go
internal/testing/loading.go
internal/webhook/github/provider_test.go
internal/webhook/gitlab/provider_test.go

From the code smells detected by [golangci-lint](https://golangci-lint.run/).
See PR #157 for CI/CD integration.
If fixes the following lint warnings:
```
internal/burrito/config/config.go:126:14: Error return value of `v.BindPFlags` is not checked (errcheck)
v.BindPFlags(flags)
^
internal/burrito/config/config.go:154:13: Error return value of `v.BindEnv` is not checked (errcheck)
v.BindEnv(strings.Join(append(parts, tv), "."))
^
internal/controllers/terraformpullrequest/comment/default.go:69:25: Error return value of `defaultTemplate.Execute` is not checked (errcheck)
defaultTemplate.Execute(comment, data)
^
internal/testing/loading.go:40:18: Error return value of `filepath.WalkDir` is not checked (errcheck)
filepath.WalkDir(path, func(path string, d fs.DirEntry, err error) error {
^ …
```

fix(lints): fix code smell detected by golangci-lint

---

internal/webhook/github/provider.go

fix(github): correctly handle PR events

---

ui/Dockerfile
ui/README.md

Add proper documentation for the Burrito UI.

feat(doc): add UI documentation

---

deploy/charts/burrito/templates/rbac.yaml
internal/controllers/terraformlayer/controller.go
internal/controllers/terraformpullrequest/comment/templates/comment.md
internal/controllers/terraformpullrequest/conditions.go
internal/controllers/terraformpullrequest/controller.go
internal/controllers/terraformpullrequest/layer.go
internal/controllers/terraformpullrequest/states.go
internal/controllers/terraformrun/controller.go
internal/webhook/event/pullrequest.go
internal/webhook/event/push.go

- **PR controller: delete linked layers in discovery just before creating new ones**
- Previously new layers were created (with GenerateName), thus when a PR was updated outdated layers were still planned, resulting in confusing results in the comment.
- Another strategy would have been to update the existing layers (this was implemented but never done because of the GenerateName uniqueness), but you also have to provide a value to `metadata.resourceVersion` when doing so, delete and re-create is simpler IMO.
- When handling push events, only inspect the layers linked to the affected repositories
- Add a few more log entries on PR creation or resource reconciliation to improve log reading
- Fix PR comment template: Markdown headings were not displayed properly when multiple layers were …

fix(pr): multiple bugs in the PR controller

---

go.mod
internal/controllers/terraformlayer/controller.go
internal/controllers/terraformpullrequest/controller.go
internal/controllers/terraformrun/controller.go

- **All controllers: reconcile when annotations change**
- Previously the [update predicate](https://github.com/padok-team/burrito/blob/983ad07f65d31b27ef7772d27b1243d92f480130/internal/controllers/terraformpullrequest/controller.go#L119-L122) was ignoring all changes applied to a resource **apart from its spec**.
- Burrito relying heavily on annotations to trigger changes on its resources, I find it useful to reconcile upon annotation changes.
- ⚠️ **Note that this can have unintended side-effect.** I made that change initially for triggering a re-sync on layers when their LastRelevantCommit changes (e.g. when a Push event is received by the Webhook).

fix(controllers): reconcile on annotation update

---

Dockerfile
internal/server/server.go

This PR:
- updates the Dockerfile to build and share the Burrito UI assets to other build stage
- moves some endpoints under a common `/api`
- embed and serve the UI
⚠️ the webhook endpoint was moved from `/webhook` to `/api/webhook`

feat(ui): embed and serve UI assets from Burrito binary

---

internal/controllers/terraformpullrequest/github/provider.go
internal/controllers/terraformpullrequest/gitlab/provider.go
internal/utils/url/url.go
internal/utils/url/url_test.go
internal/webhook/event/common.go
internal/webhook/event/pullrequest.go
internal/webhook/event/push.go
internal/webhook/github/provider.go
internal/webhook/gitlab/provider.go

fix(url): normalizeURL wasn't working on https with .git suffix

---

ui/Dockerfile
ui/README.md
ui/package.json
ui/src/components/cards/Card.tsx
ui/src/components/tables/Table.tsx
ui/src/pages/layers/Layers.tsx
ui/src/pages/layers/components/RepositoryDropdown.tsx
ui/yarn.lock

This PR:
- upgrades `tailwind-merge` from v1 to v2. Contains breaking changes but no updated required on our side according to https://github.com/dcastil/tailwind-merge/blob/v2.0.0/docs/changelog/v1-to-v2-migration.md
- migrates `tanstack-query` from v4 to v5. Contains breaking changes, updates were made according to https://tanstack.com/query/latest/docs/react/guides/migrating-to-v5
- includes other minor packages upgrades
- updates UI dockerfile to node 20
- fixes a bug with tooltip which might get stuck (https://react-tooltip.com/docs/troubleshooting#the-tooltip-doesnt-close)
- fixes doc

chore(ui): upgrade UI node dependencies

---

ui/src/components/buttons/Toggle.tsx
ui/src/components/misc/ThemeToggle.tsx
ui/src/pages/layers/Layers.tsx

Small improvement in the UX 😄 
This makes the label part of the Toggle component to makes it clickable.

feat(ui): add label prop to toggle component

---

ui/src/pages/layers/Layers.tsx

This PR makes use of URL search parameters for filtering layers in the UI. It provides better sharable links.
Fixes #216

feat(ui): use search parameters when filtering

---

internal/server/api/layers.go

This removes an unecessary API call that makes the server's LayersHandler very slow (1 api call is made per layer when listing layers). This drastically improves UI performances.

fix(server): Remove unused api call to repository on layer state get

---

internal/controllers/terraformpullrequest/comment/templates/comment.md

Enable syntax coloring for terraform plans on PRs
Turns this:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_s3_bucket" "example" {
+ acceleration_status         = (known after apply)
+ acl                         = (known after apply)
+ arn                         = (known after apply)
+ bucket                      = "my-tf-test-bucket"
+ bucket_domain_name          = (known after apply)
+ bucket_prefix               = (known after apply)
+ bucket_regional_domain_name = (known after apply)
+ force_destroy               = false
+ hosted_zone_id              = (known after apply)
+ id                          = (known after …
```

Enable syntax coloring for terraform plans on PRs

---

ui/src/components/inputs/Dropdown.tsx
ui/src/components/inputs/Input.tsx
ui/src/pages/layers/components/RepositoriesDropdown.tsx
ui/src/pages/login/Login.tsx

I noticed ugly text wrapping in a dropdown while drafting PR #220. To fix this, I also needed to rework the input component which broke the login page because of bad CSS I wrote. It's also fixed now.

refactor(ui): rework input and dropdown without text wrapping

---

deploy/charts/burrito/templates/rbac.yaml
internal/controllers/manager.go
internal/controllers/terraformlayer/controller.go
internal/controllers/terraformlayer/controller_test.go
internal/controllers/terraformlayer/run.go
internal/controllers/terraformlayer/states.go
internal/controllers/terraformpullrequest/controller.go
internal/controllers/terraformpullrequest/controller_test.go
internal/controllers/terraformpullrequest/layer.go
internal/controllers/terraformpullrequest/states.go
internal/controllers/terraformrepository/controller.go
internal/controllers/terraformrun/controller.go
internal/controllers/terraformrun/controller_test.go
internal/controllers/terraformrun/states.go

One of the main feedback from Burrito users was that it is quite difficult to debug as it is easy to  misconfigure something (tenants, serviceaccounts, cloud IAM...). This PR implements some logging from the controller using Kubernetes events. Hopefully this would make Burrito easier to install and to debug for users.

feat(controllers): add logging with k8s events

---

deploy/charts/burrito/README.md
deploy/charts/burrito/templates/config.yaml
deploy/charts/burrito/templates/controllers.yaml
deploy/charts/burrito/templates/datastore.yaml
deploy/charts/burrito/templates/hermitcrab.yaml
deploy/charts/burrito/templates/issuer.yaml
deploy/charts/burrito/templates/server.yaml
deploy/charts/burrito/values.yaml

This adds comments to all values in the helm chart to better understand what is configurable. I used https://github.com/norwoodj/helm-docs to automatically generate a README file as helm chart documentation.
Most importantly, this PR also makes cert-manager not required to run Burrito and disables TLS for the datastore in the chart default values. This aims at easing the installation process for Burrito, while making clear that using TLS is strongly recommended and very easy to setup with cert-manager.

feat(chart): update values & doc to get started easier

---

deploy/charts/burrito/templates/controllers.yaml
deploy/charts/burrito/templates/datastore.yaml
deploy/charts/burrito/templates/server.yaml
deploy/charts/burrito/values.yaml

Hi!
We use Vault CSI to gather secrets from Hashicorp Vault and it requires to mount a CSI volume to actually get them.
The option `extra*Volumes` was already define for `hermitcrab.yaml` template.

allow add extra volumes and mounts in Helm chart

---

deploy/charts/burrito/values.yaml
docs/operator-manual/datastore.md
internal/burrito/config/config.go
internal/datastore/storage/s3/s3.go

Allow configuration of path style option on AWS S3 SDK.
This allow usage of S3 compatible solutions other than AWS S3.

feat(datastore): datastore S3 use path style configuration

---

renovate.json

Inpired by the [`padok-team/renovate-config`](https://github.com/padok-team/renovate-config/blob/main/default.json) defaults, this Renovate config file is more suited to Burrito, stopping pinning GitHub Actions for example (reducing the load of PRs generated by Renovate).

chore(renovate): update renovate config file

---

cmd/controllers/start.go
deploy/charts/burrito/templates/config.yaml
deploy/charts/burrito/values.yaml
internal/burrito/config/config.go
internal/burrito/config/config_test.go
internal/burrito/config/testdata/test-config-1.yaml
internal/controllers/terraformrun/pod.go

This update adds a configuration parameter to set the default repository, tag, and pull policy for the image used in runner pods.
Previously, to use a custom image for all Burrito pods (often necessary during development), we had to override the image in both the chart's values and the spec.overrideRunnerSpec field of a TerraformLayer or TerraformRepository resource.

feat: set default runner image in global config

---

internal/datastore/storage/s3/s3.go

According to https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax, for `ListObjectsV2`, the Prefix must:
* not begins with a `/`
* ends with a `/`
But curently, the used prefix is something like `/layers/<namespace>/<layer>/<run>`.
So we need to transform it like `layers/<namespace>/<layer>/<run>/` to get some list results.
fix https://github.com/padok-team/burrito/issues/332

fix(datastore): correct prefix to list with S3 storage

---

docs/examples/terraform-repository.yaml

Example files does not reflect the change in v0.5.0. The documentation refers to the parameter terraform.enabled = true but the file used with kubectl apply does not reflect this change.

doc: fix example file after v0.5.0 update

---

renovate.json

fix(renovate): wrong manager for docker

---

deploy/charts/burrito/templates/tenant.yaml
docs/operator-manual/multi-tenant-architecture.md

The default service account used for runner pods is called `burrito-runner`(see `internal/controllers/terraformrun/pod.go`).
Currently, you either:
- Create this specific service account in tenants
- Create a service account with an other name, and reference it with `overrideRunnerSpec.serviceAccountName` in layers and/or repositories

feat(chart): add a default service account for runner pods

---

api/v1alpha1/common.go
api/v1alpha1/common_test.go

fix issue #313
Breaking changes: terraform layer tolerations (if exist) override completely terraform repository tolerations.
Allows multiple tolerations with same key but different values.

fix(api): override tolerations instead of merging them

---

docs/contributing.md

The manifests that are being provided as testing examples on contributing [page](https://padok-team.github.io/burrito/contributing/#basic-install) had some indentation issues namely:
* `repository.name`, `repository.namespace`
`repository.url`, `terraform.enabled`, `opentofu.enabled`, `terragrunt.enabled`

docs(contributing): Fix indentation on manifests provided as examples

---

.github/workflows/ci-frontend.yaml
.github/workflows/ci.yaml
renovate.json

This PR reduces Renovate PRs on frontend dependencies (all deps will be in one PR) and splits the CI between the operator and the frontend to reduce CI times

chore(ui): separate renovate and CI/CD

---

internal/datastore/storage/azure/azure.go

Add config in the Azure struct.
Needed to use the right container. Without that, the datastore writes in a "layers" blob container and the list of the blob files doesn't work.

fix(datastore): add config in Azure struct

---

Dockerfile

- Use `-s -w` to strip debug symbols. On Linux/ARM64 `burrito` binary goes from ~120MB to ~80MB.
- Remove `-a` option to `go build` because it was rebuilding all the packages from scratch, thus not using the cache. This will speed up builds on local machines.

fix(docker): reduce binary size + speed up build

---

ui/src/pages/Layers.tsx

The layer cards are currently stretched on the whole screen on the main page. (happens when you have < 3 layers)
It's now limited to a third of the screen to make it more consistent with the view displayed when there are >= 3 layers
1 layer:
2 layers:
Small screen size:

feat(ui): limit width of layer cards to a third of the grid

---

.github/workflows/ci.yaml

This will save time on Renovate PRs fixing other areas that Go dependencies (for example UI dependencies)

chore(ci): only run Golang CI on specific changes

---

.github/workflows/build-and-push.yaml
.github/workflows/ci-frontend.yaml
.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/helm.yaml

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

chore(ci): use arm64 runners

---

deploy/charts/burrito/templates/config.yaml
deploy/charts/burrito/templates/tenant.yaml
deploy/charts/burrito/values-dev.yaml
deploy/charts/burrito/values.yaml

Fixes #512 
In tenants where no custom service accounts were defined in the Helm chart:
- the default `burrito-runner` ServiceAccount was missing a RoleBinding for interacting with Repos/Layers + an entry in the authorized SA list of the datastore
- the `burrito-system/burrito-server` SA was missing a Role+RoleBinding for reading secrets in this tenant (mandatory for reading webhook secret in the new Git provider config)

fix(chart): add rbac for default SA + server in each tenant

---

CONTRIBUTING.md
README.md
deploy/charts/burrito/values.yaml
docs/CNAME
docs/contributing.md
docs/operator-manual/pr-mr-workflow.md
internal/controllers/terraformpullrequest/controller.go

Domain name is already setup in repository's setting. This PR replaces all references of all domain to the new one.

docs: update domain name to docs.burrito.tf

---

api/v1alpha1/common.go
api/v1alpha1/common_test.go
internal/controllers/terraformrun/pod.go
manifests/crds/config.terraform.padok.cloud_terraformlayers.yaml
manifests/crds/config.terraform.padok.cloud_terraformrepositories.yaml
manifests/install.yaml

Using the helm chart, I successfully installed the CRDs, I now see the affinity 
(also made sure to override the `appVersion` in Chart.yaml with the name of the branch, using the image: `ghcr.io/padok-team/burrito:feat-terraform-repository-crd-affinity`)
deployed a `TerraformLayer` + `TerraformRepository` using the following manifests
```yaml
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
name: test-affinity
namespace: burrito
spec:
branch: main
overrideRunnerSpec:
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: "app.kubernetes.io/instance"
operator: In
values:
- argocd
topologyKey: kubernetes.io/hostname
path: utils/terraform-gke/
remediationStrategy:
autoApply: false
repository:
name: …
```

feat(crd): support affinity in overriderunnerspec

---

internal/controllers/terraformpullrequest/controller_test.go
internal/controllers/terraformpullrequest/layer.go

Layers generated during the PR / MR flow do not inherit all properties from the original layer. Especially, Terragrunt and OpenTofu setup properties are not inherited, breaking the layer plan/apply.
To prevent this from happening again, I added a small test to check that a layer generated from a PR has the same spec as the original one (except for `branch` and `autoApply` field which may be different)

fix(pullrequests): inherit all properties from original layer in pr layer

---

internal/runner/tools/opentofu/opentofu.go

logs from opentofu runs are hard to read because of the symbols used to show colors in the terminal:
you use the terraform-exec library for running terraform commands, which has `-no-color` set for all commands
- https://github.com/hashicorp/terraform-exec/blob/main/tfexec/init.go#L192
- https://github.com/hashicorp/terraform-exec/blob/main/tfexec/plan.go#L194
- https://github.com/hashicorp/terraform-exec/blob/main/tfexec/show.go#L215
- https://github.com/hashicorp/terraform-exec/blob/main/tfexec/apply.go#L176
so i have added this flag to all opentofu commands, and the output is readable now:
tested by running my own version of the controller image: https://hub.docker.com/layers/rssnyder/burrito/dev/images/sha256-86c98df34408aa00c906950531dbb60f0578fcf7d091e006aeeea6cdc5ddde16

fix: [opentofu] no color

---

deploy/charts/burrito/templates/datastore.yaml
deploy/charts/burrito/templates/server.yaml

Currently the value for service type in the helm chart uses the top level `service` key in the global or component level values.
We should instead use the `service` group under both those respective sections to set the type of the services deployed.
(i use LoadBalancers for internal services, and would rather not expose via ingress)
this would break existing installs if they are seeing this value in its current location.

fix: [deploy] service type use service group value

---

api/v1alpha1/terraformrepository_types.go
cmd/controllers/start.go
deploy/charts/burrito/values.yaml
docs/operator-manual/advanced-configuration.md
docs/operator-manual/runner-scheduling.md
internal/burrito/config/config.go
internal/burrito/config/config_test.go
internal/burrito/config/testdata/test-config-1.yaml
internal/controllers/terraformrun/controller_test.go
internal/controllers/terraformrun/pod.go
internal/controllers/terraformrun/states.go
internal/controllers/terraformrun/testdata/controller/parallel-case.yaml
internal/controllers/terraformrun/testdata/controller/repository-layers.yaml
manifests/crds/config.terraform.padok.cloud_terraformrepositories.yaml
manifests/install.yaml
mkdocs.yml

This PR adds a `MaxConcurrentRunnerPods` setting that can be set in the controller config and overriden in the TerraformRepository spec.
The setting defines the maximum number of concurrently running pods for burrito runners. No limit is defined if the setting is set to 0 (default).
The purpose of this is to limit the sudden burst in the amount workloads in the k8s cluster when a high amount of layers need to be planned or applied.

feat: add setting to limit the number of concurrent runner pods

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/release.yaml

This is for reducing Renovate PRs load on actions. Let's stay on major versions for now.

chore(ci): remove digests in actions versions

---

docs/operator-manual/datastore.md

This PR adds documentation to use a private s3 endpoint.
This also completes #317

docs(datastore): use a private s3 endpoint

---

cmd/controllers/controller.go
cmd/datastore/datastore.go
cmd/runner/runner.go
cmd/server/server.go
internal/utils/cmd/cmd.go

This PR returns rc=2 for unsupported commands. 
Before, if you override the `args` for a component with a mistake, it happily returned 0. This can be misleading once in k8s, especially on the runner part which shown a `Completed` status whereas it totally crashed.
Now this returns a different rc and an error:
```bash
╰ go build -o bin/burrito main.go && bin/burrito server unsupportedcommand ; echo $?
Error: unknown server subcommand: unsupportedcommand
Run 'burrito server --help' for usagecmd to use burrito's server
Usage:
burrito server [flags]
burrito server [command]
Available Commands:
start       Start burrito's server
Flags:
-h, --help   help for server
Use "burrito server [command] --help" for more information about a command.
2
```

fix: return rc=2 for unsupported commands

---

docs/user-guide/additionnal-trigger-path.md

This PR precises that `config.terraform.padok.cloud/additionnal-trigger-paths` can be comma-separated as per code at https://github.com/padok-team/burrito/blob/8a615ec9cf9ea903f5f3bb54f312cea445ddf3ab/internal/controllers/terraformlayer/conditions.go#L285

docs: precise trigger paths can be comma-separated

---

internal/datastore/storage/s3/s3.go

The Check operation on the datastore was not working as expected when using S3 (tested with MinIO):
- NotFound error was not correctly checked
- A nil-pointer dereference exception was raised on the checksum because S3 does not set a checksum by default in its responses.

fix(datastore): handle not found error for S3 HeadObject

---

internal/datastore/storage/s3/s3.go

Fixes #602 by checking `ChecksumAlgorithmSha256` support on the s3 bucket
The check is made only on datastore startup

fix(s3): remove ChecksumAlgorithm

---

deploy/charts/burrito/templates/ssh-known-hosts.yaml

This PR fixes the multiline formatting for the known_hosts field in the SSH ConfigMap template.
The change replaces the plain `:` with `|-` to properly handle multiline strings in the Helm chart, ensuring SSH known hosts are correctly formatted when deployed.

fix(chart): known_hosts multiline formatting

---

go.mod
go.sum
internal/runner/tools/base/base.go
internal/runner/tools/install.go
internal/runner/tools/opentofu/opentofu.go
internal/runner/tools/terraform/terraform.go

Fix https://github.com/padok-team/burrito/issues/598
Changes made:
- Replaced terraform-exec library: Migrated from hashicorp/terraform-exec to direct os/exec commands
- Created shared base: New internal/runner/tools/base/base.go with BaseTool struct containing all common functionality

fix(tools): remove terraform-exec

---

.github/workflows/docs.yaml
mkdocs.yml

Fixes #593
For each release it deploys a new version linked to the release name and update the "latest" alias.
For each push on the main branch it pushes a new version of the doc under the "unstable" alias.
By default, visitors of https://docs.burrito.tf will be presented the "latest" version of the documentation.
Once this PR merged I will push a version of the doc for 0.7.0/latest from the tag v0.7.0

docs: add multi-versioning doc

---

Dockerfile

Fixed Docker image permissions by ensuring the entire /home/burrito directory is owned by the burrito user
This solve an issue I've seen with the terraform helm provider when trying to write into `~/.cache`

fix(docker): chown burrito user home directory

---

internal/runner/tools/install.go
internal/runner/tools/terragrunt/terragrunt.go
internal/runner/tools/terragrunt/terragrunt_test.go

This PR fixes #661: it handles new terragrunt 0.73.0+ flags. Deprecated flags have been removed in 0.85.0

fix: handle terragrunt 0.73.0+ new flags

---

internal/controllers/terraformlayer/conditions.go
internal/controllers/terraformlayer/controller_test.go
internal/controllers/terraformlayer/testdata/unknown-cases.yaml

Fixes #591 
Since there are owner references between runs and associated pods, it makes sense to consider the status of the layer as not running when runs associated to the last action are not found by the controller.

fix(layer-controller): consider layer not running when runs are not found

---

go.mod
go.sum
internal/datastore/storage/s3/s3.go
internal/datastore/storage/storage_test.go

We were using the V1 AWS SDK only for the aws.String type, that is also provided by aws sdk V2.
AWS SDK v1 is [deprecated](https://aws.amazon.com/fr/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/) since July 31, 2025

chore(deps): remove aws-sdk v1

---

deploy/charts/burrito/crds/crd-terraformlayers.yaml
deploy/charts/burrito/crds/crd-terraformpullrequests.yaml
deploy/charts/burrito/crds/crd-terraformrepositories.yaml
deploy/charts/burrito/crds/crd-terraformruns.yaml
deploy/charts/burrito/templates/crds/crd-terraformlayers.yaml
deploy/charts/burrito/templates/crds/crd-terraformpullrequests.yaml
deploy/charts/burrito/templates/crds/crd-terraformrepositories.yaml
deploy/charts/burrito/templates/crds/crd-terraformruns.yaml
deploy/charts/burrito/values.yaml

Reverts padok-team/burrito#663
Actually this PR was a breaking change that removes the CRDs on existing Burrito installations. For now we gonna keep the existing process.
WDYT @michael-todorovic is there a smooth way that can permit to not install CRD when needed but does not impact existing Burrito installations ?
[See Helm docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)

Revert "fix: move crds to allow helm --skip-crds usage"

---

Makefile
deploy/charts/burrito/templates/crds/config.terraform.padok.cloud_terraformlayers.yaml
deploy/charts/burrito/templates/crds/config.terraform.padok.cloud_terraformpullrequests.yaml
deploy/charts/burrito/templates/crds/config.terraform.padok.cloud_terraformrepositories.yaml
deploy/charts/burrito/templates/crds/config.terraform.padok.cloud_terraformruns.yaml
deploy/charts/burrito/templates/crds/crd-terraformlayers.yaml
deploy/charts/burrito/templates/crds/crd-terraformpullrequests.yaml
deploy/charts/burrito/templates/crds/crd-terraformrepositories.yaml
deploy/charts/burrito/templates/crds/crd-terraformruns.yaml
deploy/charts/burrito/values.yaml

This PR replaces #663. After googling for alternatives, I keep CRDs inside the `templates` folder as this allows easier CRDs  upgrades, without needing a separate chart yet. 
Helm can't read the filesystem and CRDs are autogenerated so I copy manifests thanks to Makefile, adding the conditional at the same time. By default, the PR keeps CRDs management enabled.
This PR is part of a bigger work to allow multi-instances of Burrito on the same k8s cluster. RBAC installation control is next, then a code update will land as well. It's easier to review this way :)

feat: allow control of CRDs installation
